In [2]:
import torch
import numpy as np

In [3]:
a = torch.ones(5)
b = a.numpy()
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b) # numpy() 和 from_numpy() 将 Tensor 和NumPy中的数组相互转换。但是需要注意的⼀点是： 这两个函数所产⽣的的 Tensor 和NumPy中的数组共享相同的内存

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [4]:

a = np.ones(4)
b = torch.from_numpy(a)

print(a,b)
a += 1
print(a,b)
b += 1
print(a,b)#在CPU上的 Tensor （除了 CharTensor ）都⽀持与NumPy数组相互转换

[1. 1. 1. 1.] tensor([1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2.] tensor([2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3.] tensor([3., 3., 3., 3.], dtype=torch.float64)


In [7]:
c = torch.Tensor(a)
a += 1
print(a, c) #为拷贝复制，会产生新的内存

[4. 4. 4. 4.] tensor([3., 3., 3., 3.])


In [8]:
x = torch.eye(3)
if torch.cuda.is_available():
 device = torch.device("cuda") # GPU
 print(x)
 y = torch.ones_like(x, device=device) # 直接创建⼀个在GPU上的Tensor
 print(y)
 x = x.to(device) # 等价于 .to("cuda")
 print(x)
 z = x + y
 print(z)
 print(z.to("cpu", torch.double)) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], device='cuda:0')
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], dtype=torch.float64)
