In [17]:
import torch

x =  torch.empty(5,3)
print(x) 

tensor([[3.1275e-02, 1.9366e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [18]:
x = torch.rand(5,3)
print(x)

tensor([[0.2093, 0.0576, 0.4569],
        [0.3780, 0.7079, 0.7866],
        [0.1397, 0.4472, 0.2856],
        [0.1539, 0.6192, 0.6796],
        [0.9550, 0.1893, 0.6442]])


In [19]:
x = torch.zeros(4,dtype=torch.int)
print(x)

tensor([0, 0, 0, 0], dtype=torch.int32)


In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [21]:
x = x.new_ones(5, 3, dtype=torch.float64) # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [24]:
x = torch.randn_like(x,dtype=float)
print(x)

tensor([[ 0.1206, -0.8799,  1.4684],
        [-0.3820, -0.1116,  0.7325],
        [-1.4179,  1.1344,  0.8563],
        [-1.1766,  1.7836,  0.1512],
        [-1.2844,  1.3951, -2.1880]], dtype=torch.float64)


In [60]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.size())
x = torch.tensor([[1],[2],[3]])
print(x.shape)
x = torch.tensor([[1,2,3]])
print(x.size())
x = torch.tensor([1,2,3])
print(x.size())

torch.Size([2, 3])
torch.Size([3, 1])
torch.Size([1, 3])
torch.Size([3])


In [27]:
y = torch.Tensor(x)
print(y)

tensor([[ 0.1206, -0.8799,  1.4684],
        [-0.3820, -0.1116,  0.7325],
        [-1.4179,  1.1344,  0.8563],
        [-1.1766,  1.7836,  0.1512],
        [-1.2844,  1.3951, -2.1880]], dtype=torch.float64)


In [28]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [29]:
x = torch.ones(12)
print(x)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [30]:
x = torch.zeros(5)
print(x)

tensor([0., 0., 0., 0., 0.])


In [39]:
x = torch.eye(4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [34]:
x =  torch.arange(1,11,2) #左闭右开，类似于C++STL的迭代器end();
print(x)

tensor([1, 3, 5, 7, 9])


In [40]:
x = torch.linspace(1,100,5) #t同上左闭右开
print(x)

tensor([  1.0000,  25.7500,  50.5000,  75.2500, 100.0000])


In [64]:
x = torch.rand(5) #[0, 1) 区间内均匀分布的随机数
print(x)

x = torch.randn(5)
print(x)

# 创建一个形状为 (3, 4) 的张量，并用 [a, b) 均匀分布填充  _原地操作
x = torch.empty(3, 4).uniform_(2, 5)  # 范围 [2, 5)
print(x)

tensor([0.4937, 0.7037, 0.4219, 0.9042, 0.0612])
tensor([-0.9308,  0.7644, -1.4481, -0.9173,  0.2962])
tensor([[2.1784, 2.5972, 4.4487, 2.7057],
        [3.0783, 3.2809, 3.4854, 4.9846],
        [2.4863, 4.8747, 3.8316, 2.5348]])


In [62]:
x = torch.normal(0,1,size = (1,6)) # 依次是均值，标准差，形状
print(x)

y = torch.normal(x,2)
print(y)

# mean 形状 (2, 1), std 形状 (2,)
mean = torch.tensor([[1.0], [2.0]])  # shape (2, 1)
std = torch.tensor([0.1, 0.2])       # shape (2,)

# 广播后形状为 (2, 2)，输出对应位置的采样值
tensor = torch.normal(mean=mean, std=std)
print(tensor)

tensor([[ 1.0278,  1.0616,  0.1685,  2.0099,  0.5624, -0.4986]])
tensor([[-1.3253,  1.0806,  1.0141,  3.7013,  3.1195, -5.9058]])
tensor([[1.0921, 1.0121],
        [1.9861, 2.2415]])


In [65]:
m = 10
x = torch.randperm(m) #输出0到m-1的随机序列
print(x)

tensor([9, 1, 3, 2, 4, 8, 0, 6, 5, 7])
