In [3]:
import torch

In [11]:
x = torch.normal(2,2,size = (2,3)) # 均值 方差  形状
print(x)
y = torch.rand_like(x)
print(y)

print(x+y)
print(torch.add(x,y))

result = torch.empty(2, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x) # 等价于y = y.add(x)
print(y)

tensor([[-2.5356,  3.0055,  3.5947],
        [-0.0150,  1.7194,  5.7156]])
tensor([[0.4015, 0.9856, 0.9045],
        [0.8492, 0.5430, 0.8808]])
tensor([[-2.1341,  3.9911,  4.4992],
        [ 0.8342,  2.2624,  6.5964]])
tensor([[-2.1341,  3.9911,  4.4992],
        [ 0.8342,  2.2624,  6.5964]])
tensor([[-2.1341,  3.9911,  4.4992],
        [ 0.8342,  2.2624,  6.5964]])
tensor([[-2.1341,  3.9911,  4.4992],
        [ 0.8342,  2.2624,  6.5964]])


In [80]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([1.5141, 1.2513, 1.0568, 1.4136, 1.9918])
tensor([1.5141, 1.2513, 1.0568, 1.4136, 1.9918])


In [20]:
y = torch.index_select(x,dim=0,index=torch.tensor([0])) #index得是张量 dim = 0 是 行  dim = 1 = 列
print(y)

tensor([[-1.5356,  4.0055,  4.5947]])


In [22]:
z = torch.tensor([[True,True,False],[False,False,True]])
y = torch.masked_select(x,z) #x和z维度相同
print(y)

tensor([-1.5356,  4.0055,  5.7156])


In [81]:
z = x > 0 
y = torch.masked_select(x,z) 
print(y)

tensor([1.5141, 1.2513, 1.0568, 1.4136, 1.9918, 0.9264, 0.4555, 0.9974, 0.5151,
        0.4051, 0.3534, 0.5317, 0.5478, 0.9961, 0.2300, 0.8631, 0.6638, 0.3347,
        0.4907, 0.4558, 0.5565, 0.1368, 0.2828, 0.9179, 0.4255])


In [82]:
y = torch.nonzero(x) #返回非0元素下标
print(y)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4]])


In [83]:
input = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])  # shape (3, 3)

# 沿行（dim=0）收集数据
index = torch.tensor([
    [0, 1, 0],  # 第0行选第[0,0][1,1][0,2]
    [1, 2, 1]   # 第1行选第[1,0][2,1][1,2]
])  # shape (2, 3)

output = torch.gather(input, dim=0, index=index) #output[0,1] = input[index[0,1], 1] = input[1,1] = 5。
print(output)

tensor([[1, 5, 3],
        [4, 8, 6]])


In [4]:
x = torch.randn(3,5)
y = x.view(15) #要符合x的数据个数
z = x.view(-1, 5) # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size()) #注意 view() 返回的新tensor与源tensor共享内存（其实是同⼀个tensor），也即更改其中的⼀个，另
#外⼀个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察⻆度
print(x)
print(y)
print(z)

torch.Size([3, 5]) torch.Size([15]) torch.Size([3, 5])
tensor([[ 0.5987, -0.8575,  0.4789,  1.8310,  0.5837],
        [-0.9362, -0.8247, -0.6621,  0.2001, -1.0268],
        [ 1.6799, -0.3942, -0.4558, -0.6493,  0.2622]])
tensor([ 0.5987, -0.8575,  0.4789,  1.8310,  0.5837, -0.9362, -0.8247, -0.6621,
         0.2001, -1.0268,  1.6799, -0.3942, -0.4558, -0.6493,  0.2622])
tensor([[ 0.5987, -0.8575,  0.4789,  1.8310,  0.5837],
        [-0.9362, -0.8247, -0.6621,  0.2001, -1.0268],
        [ 1.6799, -0.3942, -0.4558, -0.6493,  0.2622]])


In [42]:
x += 1
print(x)
print(y)

tensor([[ 0.1631,  0.7754,  1.1291,  0.8919, -0.1491],
        [ 1.9379, -0.1015,  1.3812, -0.1887,  1.0451],
        [ 1.5668, -0.5529, -0.5099, -0.1188,  1.8559]])
tensor([ 0.1631,  0.7754,  1.1291,  0.8919, -0.1491,  1.9379, -0.1015,  1.3812,
        -0.1887,  1.0451,  1.5668, -0.5529, -0.5099, -0.1188,  1.8559])


In [43]:
x_cp = x.clone().view(15) # 拷贝复制产生新的内存
x -= 1
print(x)
print(x_cp)

tensor([[-0.8369, -0.2246,  0.1291, -0.1081, -1.1491],
        [ 0.9379, -1.1015,  0.3812, -1.1887,  0.0451],
        [ 0.5668, -1.5529, -1.5099, -1.1188,  0.8559]])
tensor([ 0.1631,  0.7754,  1.1291,  0.8919, -0.1491,  1.9379, -0.1015,  1.3812,
        -0.1887,  1.0451,  1.5668, -0.5529, -0.5099, -0.1188,  1.8559])


In [50]:
x = torch.randn(1)
print(x)
print(x.item()) #标量 Tensor 转换成⼀个Python number

tensor([0.6132])
0.6131919026374817


In [77]:
x = torch.eye(5)
x = torch.rand_like(x)
print(x)

tensor([[0.5141, 0.2513, 0.0568, 0.4136, 0.9918],
        [0.9264, 0.4555, 0.9974, 0.5151, 0.4051],
        [0.3534, 0.5317, 0.5478, 0.9961, 0.2300],
        [0.8631, 0.6638, 0.3347, 0.4907, 0.4558],
        [0.5565, 0.1368, 0.2828, 0.9179, 0.4255]])


In [78]:
print(x.trace()) # 矩阵的迹
print(x.diag()) # 矩阵的对角线元素
print(x.triu(1)) # 矩阵的上三角 可带偏移量tril为下三角

tensor(2.4336)
tensor([0.5141, 0.4555, 0.5478, 0.4907, 0.4255])
tensor([[0.0000, 0.2513, 0.0568, 0.4136, 0.9918],
        [0.0000, 0.0000, 0.9974, 0.5151, 0.4051],
        [0.0000, 0.0000, 0.0000, 0.9961, 0.2300],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.4558],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


In [58]:
y = torch.eye(5)
y.add_(y)
print(y)
print(y.mm(x))#矩阵乘法

tensor([[2., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 0., 2., 0.],
        [0., 0., 0., 0., 2.]])
tensor([[0.0021, 0.9555, 0.4786, 1.3044, 1.0483],
        [0.5731, 1.3000, 1.1682, 1.7298, 1.5510],
        [1.1582, 1.4694, 0.9653, 1.9357, 1.3230],
        [1.2337, 0.7416, 0.8225, 0.2170, 0.2023],
        [0.6618, 1.4547, 0.2510, 0.0959, 1.4271]])


In [62]:
y = x.t()转置
print(y)

tensor([[0.0010, 0.2866, 0.5791, 0.6168, 0.3309],
        [0.4777, 0.6500, 0.7347, 0.3708, 0.7274],
        [0.2393, 0.5841, 0.4826, 0.4113, 0.1255],
        [0.6522, 0.8649, 0.9678, 0.1085, 0.0479],
        [0.5242, 0.7755, 0.6615, 0.1012, 0.7135]])


In [84]:
y = torch.inverse(x)
print(y)

tensor([[-0.4907,  0.4032, -1.1857,  1.3752,  1.0809],
        [ 0.0972, -0.6774,  1.2213,  1.1637, -1.7170],
        [ 0.1478,  1.2533,  0.4291, -1.3424, -0.6789],
        [-0.1542, -0.4121,  0.6677, -0.1497,  0.9136],
        [ 0.8450, -0.2534, -0.5675, -0.9579, -0.0312]])


In [86]:
x = torch.randn(5)
y = torch.randn(5)
print(torch.dot(x,y)) #x和y为同维张量 高纬度可使用或 x @ y

tensor(1.0246)


In [88]:
a = torch.tensor([1, 0, 0])  # x轴单位向量
b = torch.tensor([0, 1, 0])  # y轴单位向量

cross_product = torch.cross(a, b)
print(cross_product)  # 输出: tensor([0, 0, 1]) (z轴单位向量) 用于计算法向量

tensor([0, 0, 1])


In [64]:
import torch

# 定义一个 3x2 的矩阵
A = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0],
                  [5.0, 6.0]], dtype=torch.float32)

# 计算 SVD
U, S, V = torch.svd(A)

print("U:\n", U)
print("S:\n", S)  # 奇异值（1D 张量）
print("V:\n", V)  # 实际是 V^T

U:
 tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])
S:
 tensor([9.5255, 0.5143])
V:
 tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])
