In [2]:
import torch

In [8]:
x = torch.arange(1, 5).view(1, 4)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]])


In [9]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 索引、 view 是不会开辟新内存的，⽽像 y = x + y 这样的运算是会新开内存的

False


In [10]:
id_before = id(y)
y[:] = y + x 
print(id(y) == id_before)
y.add_(x)
print(id(y) == id_before)
y += x
prinnt(id(y))
torch.add(x,y,out = y)


True
True


In [11]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

True
